#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v18
# autospec commit: f35655a
#
Name     : R-fNonlinear
Version  : 4041.82
Release  : 45
URL      : https://cran.r-project.org/src/contrib/fNonlinear_4041.82.tar.gz
Source0  : https://cran.r-project.org/src/contrib/fNonlinear_4041.82.tar.gz
Summary  : Rmetrics - Nonlinear and Chaotic Time Series Modelling
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-fNonlinear-lib = %{version}-%{release}
Requires: R-fBasics
Requires: R-timeDate
Requires: R-timeSeries
BuildRequires : R-fBasics
BuildRequires : R-timeDate
BuildRequires : R-timeSeries
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
univariate time series including independence and neglected
	nonlinearities. Further provides functions to investigate the chaotic
	behavior of time series processes and to simulate different types of chaotic
	time series maps.

%package lib
Summary: lib components for the R-fNonlinear package.
Group: Libraries

%description lib
lib components for the R-fNonlinear package.


%prep
%setup -q -n fNonlinear
pushd ..
cp -a fNonlinear buildavx2
popd
pushd ..
cp -a fNonlinear buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1725891929

%install
export SOURCE_DATE_EPOCH=1725891929
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/fNonlinear/COPYRIGHT.html
/usr/lib64/R/library/fNonlinear/DESCRIPTION
/usr/lib64/R/library/fNonlinear/INDEX
/usr/lib64/R/library/fNonlinear/Meta/Rd.rds
/usr/lib64/R/library/fNonlinear/Meta/features.rds
/usr/lib64/R/library/fNonlinear/Meta/hsearch.rds
/usr/lib64/R/library/fNonlinear/Meta/links.rds
/usr/lib64/R/library/fNonlinear/Meta/nsInfo.rds
/usr/lib64/R/library/fNonlinear/Meta/package.rds
/usr/lib64/R/library/fNonlinear/NAMESPACE
/usr/lib64/R/library/fNonlinear/R/fNonlinear
/usr/lib64/R/library/fNonlinear/R/fNonlinear.rdb
/usr/lib64/R/library/fNonlinear/R/fNonlinear.rdx
/usr/lib64/R/library/fNonlinear/help/AnIndex
/usr/lib64/R/library/fNonlinear/help/aliases.rds
/usr/lib64/R/library/fNonlinear/help/fNonlinear.rdb
/usr/lib64/R/library/fNonlinear/help/fNonlinear.rdx
/usr/lib64/R/library/fNonlinear/help/paths.rds
/usr/lib64/R/library/fNonlinear/html/00Index.html
/usr/lib64/R/library/fNonlinear/html/R.css
/usr/lib64/R/library/fNonlinear/tests/doRUnit.R
/usr/lib64/R/library/fNonlinear/unitTests/Makefile
/usr/lib64/R/library/fNonlinear/unitTests/runTests.R
/usr/lib64/R/library/fNonlinear/unitTests/runit.Gallery.R
/usr/lib64/R/library/fNonlinear/unitTests/runit.NonLinModelling.R
/usr/lib64/R/library/fNonlinear/unitTests/runit.NonLinPlots.R
/usr/lib64/R/library/fNonlinear/unitTests/runit.NonLinTests.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/fNonlinear/libs/fNonlinear.so
/V4/usr/lib64/R/library/fNonlinear/libs/fNonlinear.so
/usr/lib64/R/library/fNonlinear/libs/fNonlinear.so
